version: '3'

services:
  web:
    stdin_open: true
    tty: true
    container_name: my-resume
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

